//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_an_OOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALAMVIEC
    {
        public string IDCaLamViec { get; set; }
        public string IDLoaiCa { get; set; }
        public string IDNhanVien { get; set; }
        public System.DateTime NgayLam { get; set; }
    
        public virtual LOAICALAM LOAICALAM { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
