//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_an_OOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHDDATSAN
    {
        public string IDCTHDDatSan { get; set; }
        public string IDHDDatSan { get; set; }
        public string IDSan { get; set; }
        public System.DateTime NgayDat { get; set; }
        public System.DateTime GioBatDau { get; set; }
        public System.DateTime GioKetThuc { get; set; }
        public Nullable<decimal> DonGia { get; set; }
    
        public virtual HDDATSAN HDDATSAN { get; set; }
        public virtual SAN SAN { get; set; }
    }
}
