//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_an_OOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHDTONG
    {
        public string IDCTHDTong { get; set; }
        public string IDHDTong { get; set; }
        public string LoaiHoaDon { get; set; }
        public string IDHoaDonCon { get; set; }
        public Nullable<decimal> TongHoaDonCon { get; set; }
        public Nullable<decimal> TongTienHDCon { get; set; }
    
        public virtual HDTONG HDTONG { get; set; }
    }
}
