//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_an_OOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDDATSAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HDDATSAN()
        {
            this.CTHDDATSANs = new HashSet<CTHDDATSAN>();
        }
    
        public string IDHDDatSan { get; set; }
        public string IDKhachHang { get; set; }
        public Nullable<System.DateTime> NgayLapHD { get; set; }
        public Nullable<decimal> TienCoc { get; set; }
        public decimal TongTien { get; set; }
        public string TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHDDATSAN> CTHDDATSANs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
