//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_an_OOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHUYENMAI
    {
        public string IDKhuyenMai { get; set; }
        public string IDSan { get; set; }
        public string IDSuKien { get; set; }
        public string TenKhuyenMai { get; set; }
        public string MaCodeKM { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public decimal GiaTriGiam { get; set; }
        public string TrangThai { get; set; }
    
        public virtual SAN SAN { get; set; }
        public virtual SUKIEN SUKIEN { get; set; }
    }
}
