//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_an_OOP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HeThongDatSanTheThaoEntities2 : DbContext
    {
        public HeThongDatSanTheThaoEntities2()
            : base("name=HeThongDatSanTheThaoEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CALAMVIEC> CALAMVIECs { get; set; }
        public virtual DbSet<CTHDDATSAN> CTHDDATSANs { get; set; }
        public virtual DbSet<CTHDSP> CTHDSPs { get; set; }
        public virtual DbSet<CTHDTONG> CTHDTONGs { get; set; }
        public virtual DbSet<HDDATSAN> HDDATSANs { get; set; }
        public virtual DbSet<HDSP> HDSPs { get; set; }
        public virtual DbSet<HDTONG> HDTONGs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LOAICALAM> LOAICALAMs { get; set; }
        public virtual DbSet<LOAISAN> LOAISANs { get; set; }
        public virtual DbSet<LSPFOOD> LSPFOODs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<QUANTRIVIEN> QUANTRIVIENs { get; set; }
        public virtual DbSet<SAN> SANs { get; set; }
        public virtual DbSet<SPFOOD> SPFOODs { get; set; }
        public virtual DbSet<SUKIENKHUYENMAI> SUKIENKHUYENMAIs { get; set; }
        public virtual DbSet<TINHLUONG> TINHLUONGs { get; set; }
    }
}
