//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_an_OOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAN()
        {
            this.CTHDDATSANs = new HashSet<CTHDDATSAN>();
        }
    
        public string IDSan { get; set; }
        public string IDLoaiSan { get; set; }
        public string TenSan { get; set; }
        public decimal DonGia { get; set; }
        public string MoTa { get; set; }
        public string TrangThai { get; set; }
        public string TinhTrangHienTai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHDDATSAN> CTHDDATSANs { get; set; }
        public virtual LOAISAN LOAISAN { get; set; }
    }
}
