//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_an_OOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUKIENKHUYENMAI
    {
        public string IDSuKien { get; set; }
        public string TenSuKien { get; set; }
        public decimal GiaTriGiam { get; set; }
        public string MaCodeKM { get; set; }
        public string MoTa { get; set; }
        public System.DateTime NgayBatDauSK { get; set; }
        public System.DateTime NgayKetThucSK { get; set; }
        public string TrangThai { get; set; }
    }
}
